[package]
name = "alux-jsonrpc"
version = "0.1.2"
description = "Composable, interpreter-independent JSON-RPC programs for meaning-first Rust design"
documentation = "https://docs.rs/alux-jsonrpc"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
alux-ext.workspace = true
