[package]
name = "alux-ext-macros"
version = "0.1.5"
description = "Procedural macros for ALUX first-order extension and transport programs"
documentation = "https://docs.rs/alux-ext-macros"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
