[workspace]
resolver = "2"
members = [
    "alux-ext",
    "alux-ext-macros",
    "alux-http",
    "alux-http-text",
    "alux-jsonrpc",
]

[workspace.package]
version = "0.1.0"
authors = ["Tomislav Grospic <grospic@gmail.com>"]
edition = "2024"
homepage = "https://alux.network"
repository = "https://github.com/alux-network/alux-rust"
license = "MIT"
rust-version = "1.97"

[workspace.dependencies]
alux-ext = { version = "0.1", path = "alux-ext" }
alux-ext-macros = { version = "0.1", path = "alux-ext-macros" }
alux-http = { version = "0.1", path = "alux-http" }
alux-http-text = { path = "alux-http-text" }
alux-jsonrpc = { version = "0.1", path = "alux-jsonrpc" }

extend = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full", "visit-mut"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"

[workspace.metadata.release]
push = true
tag = true
allow-branch = ["master"]
sign-commit = true
sign-tag = true
consolidate-commits = true
pre-release-commit-message = "chore: release"
