[package]
name = "alux-shape-text"
version = "0.1.0"
description = "Readable interpretation of ALUX data shapes"
documentation = "https://docs.rs/alux-shape-text"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
# Internal dependencies
alux-shape.workspace = true

[dev-dependencies]
# External dependencies
alux-ext.workspace = true
serde.workspace = true
