[package]
name = "alux-tokio"
description = "Tokio interpreters for domain-neutral ALUX Rust capabilities"
documentation = "https://docs.rs/alux-tokio"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
alux-sdk.workspace = true
futures.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true

[dev-dependencies]
alux-ext.workspace = true
futures.workspace = true

[lints]
workspace = true
