[package]
name = "alux-ext"
version = "0.1.2"
description = "Meaning-first Rust extensions with first-order operation defunctionalization"
documentation = "https://docs.rs/alux-ext"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
alux-ext-macros.workspace = true
extend.workspace = true

[dev-dependencies]
tokio.workspace = true
